version: "3.8"
services:
  nuxeo:
    image: nuxeo-es-japanese:2023.1.0-SNAPSHOT
    ports:
      - "8080:8080"
      - "8787:8787"
    environment:
      - TZ= "US/Pacific"
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8787
      - NUXEO_DEV=true
      - NUXEO_CLID=${NUXEO_CLID}
      - NUXEO_PACKAGES=nuxeo-web-ui
    volumes:
      - ./conf.d:/etc/nuxeo/conf.d
      - nuxeo_data:/var/lib/nuxeo
  opensearch:
    build:
      context: .
      dockerfile: ./docker/build_es/Dockerfile
      args:
      - "OPENSEARCH_IMAGE=${OPENSEARCH_IMAGE}"
    image: opensearch:1.3.11-JA
    env_file:
      - ./.env
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=opensearch
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    volumes:
      - "opensearch_data:/usr/share/opensearch/data"
volumes:
  nuxeo_data: {}
  opensearch_data: {}
