version: '2'
services:
  nuxeo:
    build: ./build_nuxeo
    image: nuxeo:10.10-JA
    ports:
    - "8080:8080"
    - "8787:8787"
    environment:
    - TZ=US/Pacific
    - NUXEO_DEV_MODE=true
    - "NUXEO_ES_HOSTS=elasticsearch:9300"
    - "NUXEO_TEMPLATES=/opt/nuxeo/custom_templates/nuxeo-es-japanese"
    - NUXEO_CLID=${CLID}
    - NUXEO_PACKAGES= ${STUDIO}
    - NUXEO_ES_CLUSTER_NAME=docker-cluster
    - "NUXEO_CUSTOM_PARAM=JAVA_OPTS=$$JAVA_OPTS -Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n\nelasticsearch.httpReadOnly.baseUrl=http://elasticsearch:9200"
    volumes:
    - "nuxeo_data:/var/lib/nuxeo/data"
    - "./nuxeo_templates:/opt/nuxeo/custom_templates/"
    links:
    - elasticsearch
  elasticsearch:
    build: ./build_es
    image: elasticsearch:6.5.4-JA
    ports:
    - "9200:9200"
    environment:
    - cluster.name=docker-cluster
    - "discovery.type=single-node"
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
    - "es_data:/usr/share/elasticsearch/data"
volumes:
  nuxeo_data:
  es_data:
